# Site settings
name: 安博尔德的博客
email: emberd@163.com
author: 安博尔德
url: http://icoding.pw
resume_site: http://icoding.pw
github: https://github.com/lijixue/
baseurl: ""
description: 爱编程，爱思考，爱创造
meta_description: meta111;description111
motto: 不积跬步，无以至千里；不积小流，无以成江海。
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lijixue
highlighter: rouge

# Build settings
markdown: kramdown

baidu_analysis: f951d59fe80902d8b1a3c2aee5313c0d

port: 4001